//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCajaRegistradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientosCaja()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public int monto_apertura { get; set; }
        public int cajeroid { get; set; }
        public int cajaid { get; set; }
        public Nullable<int> total_venta_diaria { get; set; }
        public Nullable<int> total_caja_real { get; set; }
        public Nullable<int> diferencia_caja { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
