//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCajaRegistradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public int id { get; set; }
        public string codigo_barra { get; set; }
        public string nombre { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> stockmin { get; set; }
        public Nullable<int> stockmax { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_ultima_edicion { get; set; }
        public long imagenid { get; set; }
        public int prioridadid { get; set; }
        public int categoriaid { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual Imagen Imagen { get; set; }
        public virtual Prioridade Prioridade { get; set; }
    }
}
